services:
  server:
    image: php:8.2-apache
    container_name: p3-server
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    command: sh -c "docker-php-ext-install mysqli && apache2-foreground"

  db:
    image: mysql:8.0
    container_name: p3-db
    environment:
      MYSQL_ROOT_PASSWORD: root        # Usuario: root
      MYSQL_DATABASE: p3_sibw          # Nombre de la BD
      MYSQL_USER: usuario_p3           # Segundo usuario
      MYSQL_PASSWORD: root             # Contraseña del segundo usuario
    volumes:
      - ./mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin
    container_name: p3-phpmyadmin
    ports:
      - "8001:80"
    environment:
      PMA_HOST: db
    depends_on:
      - db